package gcld

type AutoGenerated struct {
	Luban        int `json:"luban"`
	SlaveNum     int `json:"slaveNum"`
	BuyGrabCost  int `json:"buyGrabCost"`
	BuyGrabNum   int `json:"buyGrabNum"`
	BuyGrabState int `json:"buyGrabState"`
	Progress     int `json:"progress"`
	BuyCost      int `json:"buyCost"`
	Buildings    []struct {
		Status     int    `json:"status"`
		Harvest    int    `json:"harvest"`
		CanChanged bool   `json:"canChanged"`
		IsChanged  bool   `json:"isChanged"`
		Type       int    `json:"type"`
		Id         int    `json:"id"`
		Name       string `json:"name"`
		SpeedUpNum int    `json:"speedUpNum"`
		TotalUpNum int    `json:"totalUpNum"`
		Lv         int    `json:"lv"`
		Intro      string `json:"intro"`
		Pos        int    `json:"pos"`
		OutputType int    `json:"outputType"`
		ResType    int    `json:"resType"`
		Output     int    `json:"output"`
		IsNew      bool   `json:"isNew"`
		HasEvent   bool   `json:"hasEvent"`
		Upgrade    []struct {
			UpgradeEnable bool `json:"upgradeEnable"`
			Time          int  `json:"time"`
			Cost          []struct {
				Type  int `json:"type"`
				Value int `json:"value"`
			} `json:"cost"`
		} `json:"upgrade"`
	} `json:"buildings"`
	Tip         bool `json:"tip"`
	TotalOutput []struct {
		Type   int `json:"type"`
		Output int `json:"output"`
	} `json:"totalOutput"`
	AutoUpbuilding []struct {
		Times  int `json:"times"`
		AreaId int `json:"areaId"`
		State  int `json:"state"`
	} `json:"autoUpbuilding"`
	AdditionMode  int `json:"additionMode"`
	AdditionRate  int `json:"additionRate"`
	AdditionCd    int `json:"additionCd"`
	BuildingWorks []struct {
		WorkId int `json:"workId"`
		State  int `json:"state"`
	} `json:"buildingWorks"`
	FreeConsNum int `json:"freeConsNum"`
	HasBandit   int `json:"hasBandit"`
}
